run:
  timeout: 5m

linters:
  disable-all: true
  # Enable specific linter
  enable:
    # default linters as of v1.59.0
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    # specific linters
    - typecheck
    - dupl
    - whitespace
    - revive
    - misspell
    - asciicheck
    - bidichk
    - errname
    - errorlint
    - exhaustive
    - goconst
    - gofmt
    - prealloc

issues:
  max-issues-per-linter: 0
  max-same-issues: 0